openapi: 3.1.0
info:
  version: 1.0.0
  title: "Contacts app"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    "Documentattion for contact storage backend-app"
tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3001
  - url: https://contacts-app-rn1m.onrender.com
paths:
  /contacts:
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/:contactId:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
